# Production configuration for al-folio
services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.6
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=production
    command: >
      jekyll build && 
      jekyll serve 
      --host 0.0.0.0 
      --port 4000
    stdin_open: true
    tty: true

