# Development configuration for al-folio with live reload
services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.6
    build: .
    # uncomment these if you are having this issue with the build:
    # /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/site.rb:509:in 'initialize': Permission denied @ rb_sysopen /srv/jekyll/.jekyll-cache/.gitignore (Errno::EACCES)
    # and fill the args values with the output of the commands on the right
    # build:
    #   args:
    #     GROUPID: # id -g
    #     GROUPNAME: # id -gn
    #     USERID: # id -u
    #     USERNAME: # echo $USER
    ports:
      - "4000:4000"  # Standard Jekyll port
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/srv/jekyll
      - .:/srv/jekyll/site  # Additional volume for site generation
    environment:
      - JEKYLL_ENV=development
      - JEKYLL_LIVERELOAD=true
      - JEKYLL_LIVERELOAD_PORT=35729
      - JEKYLL_FORCE_POLLING=true  # Better file watching on Windows
    command: >
      bundle exec jekyll serve 
      --host 0.0.0.0 
      --port 4000 
      --livereload 
      --livereload-port 35729 
      --force_polling 
      --incremental
    stdin_open: true
    tty: true
    # Development optimizations
    restart: unless-stopped
    # File watching optimizations
    tmpfs:
      - /tmp
      - /var/tmp
